name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  mappingFile:
    description: 'mapping of keywords with comment'
    required: true
    default: 'mapping.json'
outputs:
  checklist:
    description: 'The final checklist in md format'
runs:
  using: 'node12'
  main: 'dist/index.js'
