name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        mapping: ${{fromJson('{ \"mappings\": [ { \"keywords\": [\"create index\", \"createIndex\"], \"comment\": \"Indexes have been created concurrently in big tables\" } ] }')}}
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
