name: "units-test"

mappings:
  - keywords:
      - create index
      - createIndex
    comment: Indexes have been created concurrently in big tables
  - keywords:
      - connection
      - session
      - CloseableHttpClient
      - HttpClient
    comment: Resources have been closed in finally block or using try-with-resources
  - keywords:
      - RequestMapping
      - GetMapping
      - PostMapping
      - PutMapping
    comment: Endpoint URLs exposed by application use only small case
  - keywords:
      - keyword1
      - keyword2
    comment: Expert comment

on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
      - id: set_var
        run: |
          echo "${{ mappings }}"
          echo "${{fromJson(mappings)}}"

