name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
      - id: set_var
        run: |
          echo `ls`
          content=`cat keyword-comments-mapping.json`
          echo "::set-output name=packageJson::$content"
      - run: |
          echo "${{fromJson(steps.set_var.outputs.packageJson)}}"

